### ISSUE TITLE
No report is generated when a parsing error is thrown

### ISSUE THREAD

**Issue by Xander-Steinmann** [isaaceindhoven/isaac-urls-differ#1]
Sometimes no report is generated even when the indexing task has successfully completed. I think this has to do with a parsing error like this:

`(node:6052) UnhandledPromiseRejectionWarning: TypeError: text2.charAt is not a function
    at diff.commonPrefix (C:\data\isaac-urls-differ\node_modules\text-diff\diff.js:516:52)
    at diff.main (C:\data\isaac-urls-differ\node_modules\text-diff\diff.js:112:27)
    at module.exports (C:\data\isaac-urls-differ\lib\differ.js:44:29)
    at module.exports (C:\data\isaac-urls-differ\lib\report-compiler.js:79:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)`

I tried removing the page that generated this error but then another page failed (a page with the same template).

You can reproduce this on the isaac site. I'll attach my urls.json

**Comment by Xander-Steinmann** [comment]
I had the error with this page, it returns a 404 currently: https://www.isaac.nl/en/about-us/news/isaac-news/isaacus-schrijft-eigen-magento-2-development-cookbook/ but in my first index it was there
